# quickcheck, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("quickcheck02.tst");

# doc/_Chapter_Functionality.xml:131-135
gap> QC_Check([QC_ListOf(QC_PairOf(IsPosInt))],
>             l -> ForAll(l, p -> Length(p) = 2 and ForAll(p, IsPosInt)));
true

#
gap> STOP_TEST("quickcheck02.tst", 1);
